project:
  type: website

 publish:
  - id: gh-pages
    server: github 

website:
  title: "github"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



